site_name: GuideBox
repo_url: https://github.com/ast3risk-ops/guides
repo_name: Ast3risk-ops/guides
edit_uri: edit/master/docs/
site_url: https://guides.asterisk.lol
extra_css:
  - stylesheets/extra.css

theme:
  favicon: assets/img/favicon-32x32.png 
  name: material
  logo: assets/img/package.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    admonition:
      note: octicons/pencil-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
  palette:
  
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    
    
  custom_dir: overrides/
    
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - header.autohide
    - navigation.tracking
    - navigation.prune
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top

copyright: >
 Copyright &copy; 2024 Asterisk
 <br>All content under <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" target="_blank" rel="noopener noreferrer">CC-BY-SA 4.0</a>

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#c29d76"
  - group:
      enabled: !ENV CI
      plugins:
        - privacy
        - git-committers:
            enabled: true
            repository: ast3risk-ops/guides
            branch: master
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true

extra:
  generator: false
  social:
    - icon: material/web
      link: https://asterisk.lol
      name: My Website
    - icon: fontawesome/brands/github 
      link: https://github.com/ast3risk-ops
      name: My Github
    - icon: fontawesome/brands/mastodon
      link: https://social.linux.pizza/@asterisk
      name: My Mastodon
    - icon: fontawesome/solid/envelope
      link: mailto:me@asterisk.lol
      name: My Email
    - icon: fontawesome/solid/key
      link: https://i.asterisk.lol/l/pgpkey
      name: My PGP key
    - icon: fontawesome/solid/ellipsis-vertical
      link: https://asterisk.lol/socials
      name: More...

watch:
  - "includes"
  - "overrides"

markdown_extensions:
  - admonition
  - abbr
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde




nav:
  - Home:
      - Home: index.md
  - Games:
    - Games: games/README.md
    - TF2:
        - Running on Linux: games/pc/tf2/linux.md
        - Replays: games/pc/tf2/demos.md
        
  
